copy D:\Work\OpenData.Core\test.csproj D:\Work\OpenData.Core\Common\Bzway.Common.Script\Bzway.Common.Script.csproj 
copy D:\Work\OpenData.Core\test.csproj D:\Work\OpenData.Core\Common\Bzway.Common.Script\Bzway.Common.csproj 
copy D:\Work\OpenData.Core\test.csproj D:\Work\OpenData.Core\Common\Bzway.Common.Share\Bzway.Common.Share.csproj 
copy D:\Work\OpenData.Core\test.csproj D:\Work\OpenData.Core\Common\Bzway.Common.Utility\Bzway.Common.Utility.csproj 
copy D:\Work\OpenData.Core\test.csproj D:\Work\OpenData.Core\Data\Bzway.Data.Core\Bzway.Data.Core.csproj 
copy D:\Work\OpenData.Core\test.csproj D:\Work\OpenData.Core\Data\Bzway.Data.File\Bzway.Data.File.csproj 
copy D:\Work\OpenData.Core\test.csproj D:\Work\OpenData.Core\Data\Bzway.Data.Mongo\Bzway.Data.Mongo.csproj 
copy D:\Work\OpenData.Core\test.csproj D:\Work\OpenData.Core\Data\Bzway.Data.Sql\Bzway.Data.Sql.csproj 
copy D:\Work\OpenData.Core\test.csproj D:\Work\OpenData.Core\Framework\Bzway.Framework.Application\Bzway.Framework.Application.csproj 
copy D:\Work\OpenData.Core\test.csproj D:\Work\OpenData.Core\Framework\Bzway.Framework.Connect\Bzway.Framework.Connect.csproj 
copy D:\Work\OpenData.Core\test.csproj D:\Work\OpenData.Core\Framework\Bzway.Framework.Connect.Authentication\Bzway.Framework.Connect.Authentication.MicrosoftAccount.csproj 
copy D:\Work\OpenData.Core\test.csproj D:\Work\OpenData.Core\Framework\Bzway.Framework.Connect.Cookies\Bzway.Framework.Connect.Cookies.csproj 
copy D:\Work\OpenData.Core\test.csproj D:\Work\OpenData.Core\Framework\Bzway.Framework.Content\Bzway.Framework.Content.csproj 
copy D:\Work\OpenData.Core\test.csproj D:\Work\OpenData.Core\Modules\Bzway.Module.Core\Bzway.Moudle.Core.csproj 
copy D:\Work\OpenData.Core\test.csproj D:\Work\OpenData.Core\Modules\Bzway.Module.MemberClub\Bzway.Module.MemberClub.csproj 
copy D:\Work\OpenData.Core\test.csproj D:\Work\OpenData.Core\Modules\Bzway.Module.Publisher\Bzway.Module.Publisher.csproj 
copy D:\Work\OpenData.Core\test.csproj D:\Work\OpenData.Core\Modules\Bzway.Module.UserSite\Bzway.Framework.User.csproj 
copy D:\Work\OpenData.Core\test.csproj D:\Work\OpenData.Core\Modules\Bzway.Module.UserSite\Bzway.Module.Wechat.csproj 
copy D:\Work\OpenData.Core\test.csproj D:\Work\OpenData.Core\Modules\Bzway.Module.Wechat\Bzway.Module.Wechat.csproj 
copy D:\Work\OpenData.Core\test.csproj D:\Work\OpenData.Core\Server\WechatMessageServer\Bzway.Server.WechatMessage.csproj 
copy D:\Work\OpenData.Core\test.csproj D:\Work\OpenData.Core\Server\WechatMessageServer\Bzway.Wechat.MessageServer.csproj 
copy D:\Work\OpenData.Core\test.csproj D:\Work\OpenData.Core\Sites\Bzway.Site.BackOffice\Bzway.Site.BackOffice.csproj 
copy D:\Work\OpenData.Core\test.csproj D:\Work\OpenData.Core\Sites\Bzway.Site.FrontPage\Bzway.Site.FrontPage.csproj 
copy D:\Work\OpenData.Core\test.csproj D:\Work\OpenData.Core\Tests\AppTest\AppTest.csproj 
copy D:\Work\OpenData.Core\test.csproj D:\Work\OpenData.Core\Tests\Data.Test\Data.Test.csproj 
